name: py311
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - _tflow_select=2.1.0
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - alsa-lib=1.2.3
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attr=2.5.1
  - attrs=20.3.0
  - binutils_impl_linux-64=2.40
  - biopython=1.79
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2024.7.4
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2024.7.4
  - cffi=1.14.5
  - chardet=4.0.0
  - charset-normalizer=2.1.1
  - click=7.1.2
  - colorama=0.4.6
  - contourpy=1.0.7
  - cryptography=3.4.7
  - cudatoolkit=10.1.243
  - cudnn=7.6.5.32
  - cupti=10.1.168
  - curl=8.1.1
  - cycler=0.10.0
  - dbus=1.13.18
  - et_xmlfile=1.1.0
  - expat=2.3.0
  - ffmpeg=4.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.2
  - freetype=2.10.4
  - fribidi=1.0.10
  - gast=0.4.0
  - gcc_impl_linux-64=12.2.0
  - gettext=0.21.0
  - gfortran_impl_linux-64=12.2.0
  - glib=2.68.1
  - glib-tools=2.68.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.30.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.37.1
  - gsl=2.7
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - gxx_impl_linux-64=12.2.0
  - h5py=2.10.0
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - importlib-metadata=4.0.1
  - jasper=1.900.1
  - jenkspy=0.3.3
  - joblib=1.0.1
  - jpeg=9d
  - keras=2.4.3
  - keras-preprocessing=1.1.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=4.0.0
  - levenshtein=0.20.9
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=11.1.0
  - libclang13=16.0.4
  - libcups=2.3.3
  - libcurl=7.76.1
  - libdeflate=1.18
  - libedit=3.1.20210216
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.3
  - libflac=1.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=9.3.0
  - libgcrypt=1.10.1
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.1
  - libgomp=9.3.0
  - libgpg-error=1.46
  - libiconv=1.16
  - libidn2=2.3.0
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm16=16.0.4
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.15
  - libopencv=4.5.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.2
  - libprotobuf=3.15.8
  - libsanitizer=12.2.0
  - libsndfile=1.2.0
  - libsqlite=3.42.0
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=9.3.0
  - libsystemd0=253
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - libzlib=1.2.13
  - logomaker=0.8
  - lz4-c=1.9.3
  - make=4.3
  - markdown=3.3.4
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mpg123=1.31.3
  - multidict=5.1.0
  - munkres=1.1.4
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - ncurses=6.2
  - nettle=3.7.2
  - nspr=4.30
  - nss=3.64
  - numpy=1.20.2
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=4.5.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - orfipy=0.0.4
  - packaging=23.0
  - pandas=1.2.4
  - pandoc=2.19.2
  - pango=1.50.14
  - patsy=0.5.3
  - pcre=8.44
  - pcre2=10.40
  - pillow=8.2.0
  - pip=21.1.1
  - pixman=0.40.0
  - platformdirs=3.1.1
  - plotly=5.14.1
  - ply=3.11
  - pooch=1.7.0
  - protobuf=3.15.8
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pulseaudio-client=16.1
  - py-opencv=4.5.2
  - pyahocorasick=2.1.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyfastx=2.1.0
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.4
  - python-dateutil=2.8.1
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2021.1
  - pywaffle=1.0.1
  - pyyaml=5.4.1
  - qt=5.12.9
  - qt-main=5.15.8
  - r-argparse=2.2.2
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.2.3
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-blob=1.2.4
  - r-broom=1.0.4
  - r-bslib=0.4.2
  - r-cachem=1.0.8
  - r-callr=3.7.3
  - r-cellranger=1.1.0
  - r-cli=3.6.1
  - r-clipr=0.8.0
  - r-colorspace=2.1_0
  - r-conflicted=1.2.0
  - r-cpp11=0.4.3
  - r-crayon=1.5.2
  - r-curl=4.3.3
  - r-data.table=1.14.8
  - r-dbi=1.1.3
  - r-dbplyr=2.3.2
  - r-digest=0.6.31
  - r-dplyr=1.1.2
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=0.21
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-findpython=1.0.8
  - r-fontawesome=0.5.1
  - r-forcats=1.0.0
  - r-fs=1.6.2
  - r-gargle=1.4.0
  - r-generics=0.1.3
  - r-ggalluvial=0.12.5
  - r-ggplot2=3.4.2
  - r-glue=1.6.2
  - r-googledrive=2.1.0
  - r-googlesheets4=1.1.0
  - r-gridextra=2.3
  - r-gtable=0.3.3
  - r-haven=2.5.2
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.5
  - r-httr=1.4.6
  - r-ids=1.0.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.4
  - r-knitr=1.43
  - r-labeling=0.4.2
  - r-lattice=0.21_8
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.3
  - r-lubridate=1.9.2
  - r-magrittr=2.0.3
  - r-mass=7.3_60
  - r-matrix=1.5_4.1
  - r-memoise=2.0.1
  - r-mgcv=1.8_42
  - r-mime=0.12
  - r-modelr=0.1.11
  - r-munsell=0.5.0
  - r-nlme=3.1_162
  - r-openssl=2.0.6
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-prettyunits=1.1.1
  - r-processx=3.8.1
  - r-progress=1.2.2
  - r-ps=1.7.5
  - r-purrr=1.0.1
  - r-r6=2.5.1
  - r-ragg=1.2.5
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.10
  - r-readr=2.1.4
  - r-readxl=1.4.2
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-reprex=2.0.2
  - r-rlang=1.1.1
  - r-rmarkdown=2.21
  - r-rstudioapi=0.14
  - r-rvest=1.0.3
  - r-sass=0.4.6
  - r-scales=1.2.1
  - r-selectr=0.4_2
  - r-stringi=1.7.12
  - r-stringr=1.5.0
  - r-sys=3.4.2
  - r-systemfonts=1.0.4
  - r-textshaping=0.3.6
  - r-tibble=3.2.1
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.2.0
  - r-tinytex=0.45
  - r-tzdb=0.4.0
  - r-utf8=1.2.3
  - r-uuid=1.1_0
  - r-vctrs=0.6.2
  - r-viridis=0.6.3
  - r-viridislite=0.4.1
  - r-vroom=1.6.3
  - r-withr=2.5.0
  - r-xfun=0.39
  - r-xml2=1.3.4
  - r-yaml=2.3.7
  - rapidfuzz=2.13.7
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - sed=4.8
  - setuptools=52.0.0
  - sip=6.7.9
  - six=1.15.0
  - sqlite=3.35.5
  - statsmodels=0.13.5
  - sysroot_linux-64=2.12
  - tenacity=8.2.2
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.4.1
  - tensorflow-gpu=2.4.1
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.1
  - tqdm=4.60.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - urllib3=1.26.4
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - x264=1!161.3030
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
